# Generated by Django 3.2 on 2021-05-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('plataforma', models.CharField(max_length=20)),
            ],
        ),
    ]
